#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

# Now build the image layers.
#
# The specific layers to build can be passed to this script, which we then pass through below.
build_all "${IMAGE_DIR}" "$@"
