#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

${SCRIPT_DIR}/build
${SCRIPT_DIR}/test
${SCRIPT_DIR}/validate
${SCRIPT_DIR}/package
