#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

# Build our outpout variants, which are what take the individual image layers and collect the
# relevant output artifacts from them into a cohesive whole.
mkdir -p "${ARTIFACT_DIR}"

build_all "${IMAGE_DIR}/output" "$@"
copy_all "${IMAGE_DIR}/output" "${ARTIFACT_DIR}" "$@"
