#!/usr/bin/env bash
set -e

# Pull in the common helpers and reorient ourselves to the root of the repository.
source $(dirname $0)/common

# Make sure `golangci-lint` is actually available.
if ! command -v golangci-lint; then
    echo "[!] Skipping validation: \`golangci-lint\` not available"
    exit
fi

echo "[*] Starting validation."

# Create a directory for the build data to live.
if [ ! -e build/data ];then
    mkdir -p build/data
fi

# Ensure all generated code is present, then run the linter and verify our Go modules file.
echo "[*] Running \`go generate\`..."
go generate

echo "[*] Running \`golangci-lint\`..."
golangci-lint run

echo "[*] Running \`go mod verify\`..."
GO111MODULE=on go mod verify
